// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support Team",
            "url": "https://github.com/Xushengqwer/go-backend-learning",
            "email": "your_support_email@example.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/posts": {
            "get": {
                "description": "出于管理目的，根据各种过滤条件检索分页的帖子列表。使用查询参数进行过滤和分页。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-posts (管理员-帖子)"
                ],
                "summary": "按条件列出帖子 (管理员)",
                "parameters": [
                    {
                        "type": "integer",
                        "format": "uint64",
                        "description": "按精确的帖子 ID 过滤",
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "按帖子标题过滤（模糊匹配）",
                        "name": "title",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "按作者用户名过滤（模糊匹配）",
                        "name": "author_username",
                        "in": "query"
                    },
                    {
                        "enum": [
                            0,
                            1,
                            2
                        ],
                        "type": "integer",
                        "description": "按帖子状态过滤 (0=待审核, 1=已审核, 2=已拒绝)",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "enum": [
                            0,
                            1,
                            2,
                            3
                        ],
                        "type": "integer",
                        "description": "按官方标签过滤 (例如, 0=无, 1=认证)",
                        "name": "official_tag",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "按最小浏览量过滤",
                        "name": "view_count_min",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "按最大浏览量过滤",
                        "name": "view_count_max",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "created_at",
                            "updated_at"
                        ],
                        "type": "string",
                        "default": "created_at",
                        "description": "排序字段 (created_at 或 updated_at)",
                        "name": "order_by",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "default": false,
                        "description": "是否降序排序 (true 为 DESC, false/省略为 ASC)",
                        "name": "order_desc",
                        "in": "query"
                    },
                    {
                        "minimum": 1,
                        "type": "integer",
                        "format": "int",
                        "description": "页码（从 1 开始）",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "minimum": 1,
                        "type": "integer",
                        "format": "int",
                        "description": "每页帖子数量",
                        "name": "page_size",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "帖子检索成功\" // \u003c--- 修改",
                        "schema": {
                            "$ref": "#/definitions/vo.ListPostsAdminResponseWrapper"
                        }
                    },
                    "400": {
                        "description": "无效的输入参数（例如，无效的 page, page_size, status）\" // \u003c--- 修改",
                        "schema": {
                            "$ref": "#/definitions/vo.BaseResponseWrapper"
                        }
                    },
                    "500": {
                        "description": "检索帖子时发生内部服务器错误\" // \u003c--- 修改",
                        "schema": {
                            "$ref": "#/definitions/vo.BaseResponseWrapper"
                        }
                    }
                }
            }
        },
        "/admin/posts/audit": {
            "post": {
                "description": "管理员更新帖子的状态（以及可选的原因）。需要在请求体中提供审核详情。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-posts (管理员-帖子)"
                ],
                "summary": "审核帖子",
                "parameters": [
                    {
                        "description": "审核帖子请求体",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.AuditPostRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "帖子审核成功\" // \u003c--- 修改 (无 Data)",
                        "schema": {
                            "$ref": "#/definitions/vo.BaseResponseWrapper"
                        }
                    },
                    "400": {
                        "description": "无效的请求负载（例如，缺少字段，无效的状态）\" // \u003c--- 修改",
                        "schema": {
                            "$ref": "#/definitions/vo.BaseResponseWrapper"
                        }
                    },
                    "404": {
                        "description": "帖子未找到\" // \u003c-- 添加404情况",
                        "schema": {
                            "$ref": "#/definitions/vo.BaseResponseWrapper"
                        }
                    },
                    "500": {
                        "description": "审核过程中发生内部服务器错误\" // \u003c--- 修改",
                        "schema": {
                            "$ref": "#/definitions/vo.BaseResponseWrapper"
                        }
                    }
                }
            }
        },
        "/admin/posts/{id}/official-tag": {
            "put": {
                "description": "管理员更新特定帖子的官方标签。需要在 URL 路径中提供帖子 ID，并在请求体中提供标签详情。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-posts (管理员-帖子)"
                ],
                "summary": "更新帖子官方标签 (管理员)",
                "parameters": [
                    {
                        "type": "integer",
                        "format": "uint64",
                        "description": "要更新的帖子 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "更新官方标签请求体 (请求体中的 PostID 是冗余的，请使用路径中的 ID)",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateOfficialTagRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "官方标签更新成功\" // \u003c--- 修改 (无 Data)",
                        "schema": {
                            "$ref": "#/definitions/vo.BaseResponseWrapper"
                        }
                    },
                    "400": {
                        "description": "无效的请求负载，无效的标签值，或路径 ID 与请求体 ID 不匹配\" // \u003c--- 修改",
                        "schema": {
                            "$ref": "#/definitions/vo.BaseResponseWrapper"
                        }
                    },
                    "404": {
                        "description": "帖子未找到\" // \u003c--- 修改",
                        "schema": {
                            "$ref": "#/definitions/vo.BaseResponseWrapper"
                        }
                    },
                    "500": {
                        "description": "更新标签时发生内部服务器错误\" // \u003c--- 修改",
                        "schema": {
                            "$ref": "#/definitions/vo.BaseResponseWrapper"
                        }
                    }
                }
            }
        },
        "/hot-posts": {
            "get": {
                "description": "使用基于游标的分页方式，检索热门帖子列表。使用查询参数来传递游标和数量限制。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "hot-posts (热门帖子)"
                ],
                "summary": "通过游标获取热门帖子",
                "parameters": [
                    {
                        "type": "integer",
                        "format": "uint64",
                        "description": "上一页最后一个帖子的 ID，首页省略",
                        "name": "last_post_id",
                        "in": "query"
                    },
                    {
                        "minimum": 1,
                        "type": "integer",
                        "format": "int",
                        "description": "每页帖子数量",
                        "name": "limit",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "热门帖子检索成功。\" // \u003c--- 修改",
                        "schema": {
                            "$ref": "#/definitions/vo.ListPostsByUserIDResponseWrapper"
                        }
                    },
                    "400": {
                        "description": "无效的输入参数（例如，无效的 limit 或 last_post_id 格式）\" // \u003c--- 修改",
                        "schema": {
                            "$ref": "#/definitions/vo.BaseResponseWrapper"
                        }
                    },
                    "500": {
                        "description": "检索热门帖子时发生内部服务器错误\" // \u003c--- 修改",
                        "schema": {
                            "$ref": "#/definitions/vo.BaseResponseWrapper"
                        }
                    }
                }
            }
        },
        "/hot-posts/{post_id}": {
            "get": {
                "description": "通过帖子的 ID 检索特定热门帖子的详细信息。需要在 URL 路径中提供帖子 ID，并从上下文中获取 UserID。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "hot-posts (热门帖子)"
                ],
                "summary": "根据帖子 ID 获取热门帖子详情",
                "parameters": [
                    {
                        "type": "integer",
                        "format": "uint64",
                        "description": "帖子 ID",
                        "name": "post_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "热门帖子详情检索成功\" // \u003c--- 修改",
                        "schema": {
                            "$ref": "#/definitions/vo.PostDetailResponseWrapper"
                        }
                    },
                    "400": {
                        "description": "无效的帖子 ID 格式\" // \u003c--- 修改",
                        "schema": {
                            "$ref": "#/definitions/vo.BaseResponseWrapper"
                        }
                    },
                    "401": {
                        "description": "在上下文中未找到用户 ID（未授权）\" // \u003c--- 修改",
                        "schema": {
                            "$ref": "#/definitions/vo.BaseResponseWrapper"
                        }
                    },
                    "404": {
                        "description": "热门帖子详情未找到\" // \u003c-- 添加404情况",
                        "schema": {
                            "$ref": "#/definitions/vo.BaseResponseWrapper"
                        }
                    },
                    "500": {
                        "description": "检索热门帖子详情时发生内部服务器错误\" // \u003c--- 修改",
                        "schema": {
                            "$ref": "#/definitions/vo.BaseResponseWrapper"
                        }
                    }
                }
            }
        },
        "/posts": {
            "get": {
                "description": "使用基于游标的分页方式，检索特定用户的分页帖子列表。需要在查询字符串中提供用户 ID 和分页参数。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "posts (帖子)"
                ],
                "summary": "根据用户 ID 列出帖子",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户 ID",
                        "name": "user_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "format": "uint64",
                        "description": "游标（上一页最后一个帖子的 ID），首页省略",
                        "name": "cursor",
                        "in": "query"
                    },
                    {
                        "minimum": 1,
                        "type": "integer",
                        "format": "int",
                        "description": "每页帖子数量",
                        "name": "page_size",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "帖子检索成功\" // \u003c--- 修改",
                        "schema": {
                            "$ref": "#/definitions/vo.ListPostsByUserIDResponseWrapper"
                        }
                    },
                    "400": {
                        "description": "无效的输入参数（例如，缺少 user_id，无效的 page_size）\" // \u003c--- 修改",
                        "schema": {
                            "$ref": "#/definitions/vo.BaseResponseWrapper"
                        }
                    },
                    "500": {
                        "description": "检索帖子时发生内部服务器错误\" // \u003c--- 修改",
                        "schema": {
                            "$ref": "#/definitions/vo.BaseResponseWrapper"
                        }
                    }
                }
            },
            "post": {
                "description": "使用提供的详情创建一个新帖子。请求体中需要包含作者信息。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "posts (帖子)"
                ],
                "summary": "创建新帖子",
                "parameters": [
                    {
                        "description": "创建帖子请求体",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreatePostRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "帖子创建成功\" // \u003c--- 修改",
                        "schema": {
                            "$ref": "#/definitions/vo.PostResponseWrapper"
                        }
                    },
                    "400": {
                        "description": "无效的请求负载（例如，缺少字段，验证错误）\" // \u003c--- 修改",
                        "schema": {
                            "$ref": "#/definitions/vo.BaseResponseWrapper"
                        }
                    },
                    "500": {
                        "description": "创建帖子时发生内部服务器错误\" // \u003c--- 修改",
                        "schema": {
                            "$ref": "#/definitions/vo.BaseResponseWrapper"
                        }
                    }
                }
            }
        },
        "/posts/{id}": {
            "delete": {
                "description": "通过帖子的 ID 软删除一个帖子。需要在 URL 路径中提供帖子 ID。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "posts (帖子)"
                ],
                "summary": "删除帖子",
                "parameters": [
                    {
                        "type": "integer",
                        "format": "uint64",
                        "description": "帖子 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "帖子删除成功\" // \u003c--- 修改 (无 Data)",
                        "schema": {
                            "$ref": "#/definitions/vo.BaseResponseWrapper"
                        }
                    },
                    "400": {
                        "description": "无效的帖子 ID 格式\" // \u003c--- 修改",
                        "schema": {
                            "$ref": "#/definitions/vo.BaseResponseWrapper"
                        }
                    },
                    "500": {
                        "description": "删除帖子时发生内部服务器错误\" // \u003c--- 修改",
                        "schema": {
                            "$ref": "#/definitions/vo.BaseResponseWrapper"
                        }
                    }
                }
            }
        },
        "/posts/{post_id}": {
            "get": {
                "description": "通过帖子的 ID 检索特定帖子的详细信息。需要在 URL 路径中提供帖子 ID，并从上下文（例如，通过中间件）获取 UserID。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "posts (帖子)"
                ],
                "summary": "根据帖子 ID 获取帖子详情",
                "parameters": [
                    {
                        "type": "integer",
                        "format": "uint64",
                        "description": "帖子 ID",
                        "name": "post_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "帖子详情检索成功\" // \u003c--- 修改",
                        "schema": {
                            "$ref": "#/definitions/vo.PostDetailResponseWrapper"
                        }
                    },
                    "400": {
                        "description": "无效的帖子 ID 格式\" // \u003c--- 修改",
                        "schema": {
                            "$ref": "#/definitions/vo.BaseResponseWrapper"
                        }
                    },
                    "401": {
                        "description": "在上下文中未找到用户 ID（未授权）\" // \u003c--- 修改",
                        "schema": {
                            "$ref": "#/definitions/vo.BaseResponseWrapper"
                        }
                    },
                    "500": {
                        "description": "检索帖子详情时发生内部服务器错误\" // \u003c--- 修改",
                        "schema": {
                            "$ref": "#/definitions/vo.BaseResponseWrapper"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.AuditPostRequest": {
            "type": "object",
            "required": [
                "post_id",
                "status"
            ],
            "properties": {
                "post_id": {
                    "type": "integer"
                },
                "reason": {
                    "description": "omitempty 表示可选, max 限制长度",
                    "type": "string",
                    "maxLength": 255
                },
                "status": {
                    "description": "限制状态范围",
                    "maximum": 2,
                    "minimum": 0,
                    "allOf": [
                        {
                            "$ref": "#/definitions/enums.Stats"
                        }
                    ]
                }
            }
        },
        "dto.CreatePostRequest": {
            "type": "object",
            "required": [
                "author_id",
                "author_username",
                "content",
                "title"
            ],
            "properties": {
                "author_avatar": {
                    "description": "作者头像 URL，可选",
                    "type": "string"
                },
                "author_id": {
                    "description": "作者ID，必填 (假设是 UUID 或其他非空字符串)",
                    "type": "string"
                },
                "author_username": {
                    "description": "作者用户名，必填，最大50字符",
                    "type": "string",
                    "maxLength": 50
                },
                "contact_qr_code": {
                    "description": "联系二维码 URL，可选，校验是否为 URL 或 URI (根据需要选择 url 或 uri)",
                    "type": "string"
                },
                "content": {
                    "description": "帖子内容，必填，最大1000字符",
                    "type": "string",
                    "maxLength": 1000
                },
                "price_per_unit": {
                    "description": "单价，可选，大于等于0 (omitempty 表示可选)",
                    "type": "number",
                    "minimum": 0
                },
                "title": {
                    "description": "帖子标题，必填，最大100字符",
                    "type": "string",
                    "maxLength": 100
                }
            }
        },
        "dto.UpdateOfficialTagRequest": {
            "type": "object",
            "required": [
                "official_tag",
                "post_id"
            ],
            "properties": {
                "official_tag": {
                    "description": "新的官方标签值，必填，并限制范围 (假设最大值为 3)",
                    "maximum": 3,
                    "minimum": 0,
                    "allOf": [
                        {
                            "$ref": "#/definitions/enums.OfficialTag"
                        }
                    ]
                },
                "post_id": {
                    "description": "帖子ID，必填",
                    "type": "integer"
                }
            }
        },
        "enums.OfficialTag": {
            "type": "integer",
            "enum": [
                0,
                1,
                2,
                3
            ],
            "x-enum-comments": {
                "OfficialTagCertified": "官方认证",
                "OfficialTagDeposit": "预付保证金",
                "OfficialTagNone": "无标签",
                "OfficialTagRapid": "急速响应"
            },
            "x-enum-varnames": [
                "OfficialTagNone",
                "OfficialTagCertified",
                "OfficialTagDeposit",
                "OfficialTagRapid"
            ]
        },
        "enums.Stats": {
            "type": "integer",
            "enum": [
                0,
                1,
                2
            ],
            "x-enum-comments": {
                "Approved": "1 审核通过",
                "Pending": "0 待审核",
                "Rejected": "2 拒绝"
            },
            "x-enum-varnames": [
                "Pending",
                "Approved",
                "Rejected"
            ]
        },
        "vo.BaseResponseWrapper": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "成功时为 0, 错误时为具体错误码",
                    "type": "integer",
                    "example": 0
                },
                "message": {
                    "description": "成功或错误消息",
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "vo.ListPostsAdminResponseWrapper": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 0
                },
                "data": {
                    "description": "使用具体的 vo.ListPostsByConditionResponse",
                    "allOf": [
                        {
                            "$ref": "#/definitions/vo.ListPostsByConditionResponse"
                        }
                    ]
                },
                "message": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "vo.ListPostsByConditionResponse": {
            "type": "object",
            "properties": {
                "posts": {
                    "description": "帖子列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/vo.PostAdminResponse"
                    }
                },
                "total": {
                    "description": "帖子总数",
                    "type": "integer"
                }
            }
        },
        "vo.ListPostsByUserIDResponse": {
            "type": "object",
            "properties": {
                "next_cursor": {
                    "description": "下一个游标，nil 表示无更多数据",
                    "type": "integer"
                },
                "posts": {
                    "description": "帖子列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/vo.PostResponse"
                    }
                }
            }
        },
        "vo.ListPostsByUserIDResponseWrapper": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 0
                },
                "data": {
                    "description": "使用具体的 vo.ListPostsByUserIDResponse",
                    "allOf": [
                        {
                            "$ref": "#/definitions/vo.ListPostsByUserIDResponse"
                        }
                    ]
                },
                "message": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "vo.PostAdminResponse": {
            "type": "object",
            "properties": {
                "author_avatar": {
                    "description": "作者头像",
                    "type": "string"
                },
                "author_id": {
                    "description": "作者ID",
                    "type": "string"
                },
                "author_username": {
                    "description": "作者用户名",
                    "type": "string"
                },
                "created_at": {
                    "description": "创建时间",
                    "type": "string"
                },
                "id": {
                    "description": "帖子ID",
                    "type": "integer"
                },
                "official_tag": {
                    "description": "官方标签",
                    "allOf": [
                        {
                            "$ref": "#/definitions/enums.OfficialTag"
                        }
                    ]
                },
                "status": {
                    "description": "帖子状态（0=待审核, 1=已审核, 2=拒绝）",
                    "allOf": [
                        {
                            "$ref": "#/definitions/enums.Stats"
                        }
                    ]
                },
                "title": {
                    "description": "帖子标题",
                    "type": "string"
                },
                "updated_at": {
                    "description": "更新时间",
                    "type": "string"
                },
                "view_count": {
                    "description": "浏览量",
                    "type": "integer"
                }
            }
        },
        "vo.PostDetailResponse": {
            "type": "object",
            "properties": {
                "author_avatar": {
                    "description": "作者头像",
                    "type": "string"
                },
                "author_id": {
                    "description": "作者ID",
                    "type": "string"
                },
                "author_username": {
                    "description": "作者用户名",
                    "type": "string"
                },
                "contact_qr_code": {
                    "description": "联系二维码",
                    "type": "string"
                },
                "content": {
                    "description": "帖子内容",
                    "type": "string"
                },
                "created_at": {
                    "description": "创建时间",
                    "type": "string"
                },
                "id": {
                    "description": "帖子详情ID",
                    "type": "integer"
                },
                "post_id": {
                    "description": "帖子ID",
                    "type": "integer"
                },
                "price_per_unit": {
                    "description": "单价",
                    "type": "number"
                },
                "updated_at": {
                    "description": "更新时间",
                    "type": "string"
                }
            }
        },
        "vo.PostDetailResponseWrapper": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 0
                },
                "data": {
                    "description": "使用具体的 vo.PostDetailResponse",
                    "allOf": [
                        {
                            "$ref": "#/definitions/vo.PostDetailResponse"
                        }
                    ]
                },
                "message": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "vo.PostResponse": {
            "type": "object",
            "properties": {
                "author_avatar": {
                    "description": "作者头像",
                    "type": "string"
                },
                "author_id": {
                    "description": "作者ID",
                    "type": "string"
                },
                "author_username": {
                    "description": "作者用户名",
                    "type": "string"
                },
                "created_at": {
                    "description": "创建时间",
                    "type": "string"
                },
                "id": {
                    "description": "帖子ID",
                    "type": "integer"
                },
                "status": {
                    "description": "帖子状态，0=待审核, 1=已审核, 2=拒绝",
                    "type": "integer"
                },
                "title": {
                    "description": "帖子标题",
                    "type": "string"
                },
                "updated_at": {
                    "description": "更新时间",
                    "type": "string"
                },
                "view_count": {
                    "description": "浏览量",
                    "type": "integer"
                }
            }
        },
        "vo.PostResponseWrapper": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 0
                },
                "data": {
                    "description": "使用具体的 vo.PostResponse",
                    "allOf": [
                        {
                            "$ref": "#/definitions/vo.PostResponse"
                        }
                    ]
                },
                "message": {
                    "type": "string",
                    "example": "success"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Post Service API",
	Description:      "帖子服务，提供帖子发布、查询、管理等功能。",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
